### ISSUE TITLE
How about limiting input to available autocompleteItems?

### ISSUE THREAD

**Issue by 949mac** [superlatif-io/nova-tag-input#4]
I have a list I want users to choose from. How can I set up the field so they can't enter a value that isn't in the autocompleteItems array?

Thanks!

**Comment by superlatif-io** [comment]
Hi,

thanks for your message, as of v. 1.3 (published yesterday) you can limit the tags that can be used in the field to the autocomplete items, please check the readme file.

PS: you may want to disable tag edition when using this feature, otherwise the user will be able to change a tag value afterward.

**Comment by 949mac** [comment]
@superlatif-io 

Ah! Terrific. Can I buy you a coffee? :blush:
